name: untorneo_mobile
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.1
  equatable: ^2.0.5
  flutter_riverpod: ^2.3.6
  font_awesome_flutter: ^10.4.0
  go_router: ^7.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.6
  image_picker: ^0.8.7+5
  image_picker_for_web: ^2.1.12
  intl: ^0.18.1
  lottie: ^2.3.2
  riverpod: ^2.3.6
  socket_io_client: ^2.0.2
  graphql: ^5.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/imgs/
